### ISSUE TITLE
Error when clicking ok in connect to server dialog without selecting anything

### ISSUE THREAD

**Issue by virenerus** [virenerus/tabletoptool#12]
java.lang.ArrayIndexOutOfBoundsException: -1
 at java.util.ArrayList.elementData(Unknown Source)
 at java.util.ArrayList.get(Unknown Source)
 at com.t3.client.ui.ConnectToServerDialog.handleOK(ConnectToServerDialog.java:324)
 at com.t3.client.ui.ConnectToServerDialog.access$3(ConnectToServerDialog.java:270)
 at com.t3.client.ui.ConnectToServerDialog$2.actionPerformed(ConnectToServerDialog.java:139)
 at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
 at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
 at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
 at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
 at java.awt.Component.processMouseEvent(Unknown Source)
 at javax.swing.JComponent.processMouseEvent(Unknown Source)
 at java.awt.Component.processEvent(Unknown Source)
 at java.awt.Container.processEvent(Unknown Source)
 at java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.awt.Component.dispatchEvent(Unknown Source)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 at java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.awt.Component.dispatchEvent(Unknown Source)
 at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.awt.EventQueue.access$200(Unknown Source)
 at java.awt.EventQueue$3.run(Unknown Source)
 at java.awt.EventQueue$3.run(Unknown Source)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
 at java.awt.EventQueue$4.run(Unknown Source)
 at java.awt.EventQueue$4.run(Unknown Source)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
 at java.awt.EventQueue.dispatchEvent(Unknown Source)
 at com.t3.client.swing.T3EventQueue.dispatchEvent(T3EventQueue.java:35)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.awt.WaitDispatchSupport$2.run(Unknown Source)
 at java.awt.WaitDispatchSupport$4.run(Unknown Source)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(Unknown Source)
 at java.awt.Dialog.show(Unknown Source)
 at java.awt.Component.show(Unknown Source)
 at java.awt.Component.setVisible(Unknown Source)
 at java.awt.Window.setVisible(Unknown Source)
 at java.awt.Dialog.setVisible(Unknown Source)
 at com.t3.client.swing.GenericDialog.showDialog(GenericDialog.java:79)
 at com.t3.client.ui.ConnectToServerDialog.showDialog(ConnectToServerDialog.java:95)
 at com.t3.client.AppActions$52.execute(AppActions.java:1930)
 at com.t3.client.AppActions$ClientAction.actionPerformed(AppActions.java:2800)
 at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
 at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
 at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
 at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
 at javax.swing.AbstractButton.doClick(Unknown Source)
 at com.jidesoft.plaf.vsnet.VsnetMenuItemUI.doClick(Unknown Source)
 at com.jidesoft.plaf.vsnet.VsnetMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
 at java.awt.Component.processMouseEvent(Unknown Source)
 at javax.swing.JComponent.processMouseEvent(Unknown Source)
 at java.awt.Component.processEvent(Unknown Source)
 at java.awt.Container.processEvent(Unknown Source)
 at java.awt.Component.dispatchEventImpl(Unknown Source)
 at java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.awt.Component.dispatchEvent(Unknown Source)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 at java.awt.Container.dispatchEventImpl(Unknown Source)
 at java.awt.Window.dispatchEventImpl(Unknown Source)
 at java.awt.Component.dispatchEvent(Unknown Source)
 at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.awt.EventQueue.access$200(Unknown Source)
 at java.awt.EventQueue$3.run(Unknown Source)
 at java.awt.EventQueue$3.run(Unknown Source)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
 at java.awt.EventQueue$4.run(Unknown Source)
 at java.awt.EventQueue$4.run(Unknown Source)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
 at java.awt.EventQueue.dispatchEvent(Unknown Source)
 at com.t3.client.swing.T3EventQueue.dispatchEvent(T3EventQueue.java:35)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by mbbhudgins** [comment]
Will take a look at this as part of the UI redo.

**Comment by virenerus** [comment]
Nice. I also have do change some stuff in the GUI because I am currently creating two new property types. Maybe we could coordinate this so there won't be as much merging work at the end?

**Comment by mbbhudgins** [comment]
Sounds good. What property types?

**Comment by virenerus** [comment]
I am currently working on the much struct and list properties. A struct
will allow you to define a set list of subproperties while list property
contains an arbitrary long list of subnodes of a certain type. Both
together allow you to create cool thing like allowing players easily to
enter a list of weapons with certain stats(name, damage,...).
For that the old property list has to become a tree.
