### ISSUE TITLE
Two NPE on switching to a map.

### ISSUE THREAD

**Issue by MoraFermi** [virenerus/tabletoptool#33]
This one appears to be connected to the code responsible for drawing the "hit area template".

Tentative steps to recreate:
- Create map, use the template to draw and clear several hit zones;
- Erase them;
- Save campaign, close T3;
- Open T3 again, load the campaign
- Switch to the map.

java.lang.NullPointerException
    at com.t3.util.guidreference.ZoneReference.resolveReference(ZoneReference.java:21)
    at com.t3.util.guidreference.ZoneReference.resolveReference(ZoneReference.java:1)
    at com.t3.util.guidreference.GUIDReference.value(GUIDReference.java:43)
    at com.t3.util.guidreference.CachedGUIDReference.value(CachedGUIDReference.java:24)
    at com.t3.util.guidreference.NullHelper.value(NullHelper.java:19)
    at com.t3.model.drawing.RadiusTemplate.getBounds(RadiusTemplate.java:123)
    at com.t3.client.ui.zone.PartitionedDrawableRenderer.createChunk(PartitionedDrawableRenderer.java:208)
    at com.t3.client.ui.zone.PartitionedDrawableRenderer.renderDrawables(PartitionedDrawableRenderer.java:117)
    at com.t3.client.ui.zone.ZoneRenderer.renderDrawableOverlay(ZoneRenderer.java:1745)
    at com.t3.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1081)
    at com.t3.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:689)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintChildren(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintToOffscreen(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
    at javax.swing.RepaintManager.paint(Unknown Source)
    at javax.swing.JComponent._paintImmediately(Unknown Source)
    at javax.swing.JComponent.paintImmediately(Unknown Source)
    at javax.swing.RepaintManager$3.run(Unknown Source)
    at javax.swing.RepaintManager$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.access$1100(Unknown Source)
    at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$400(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at com.t3.client.swing.T3EventQueue.dispatchEvent(T3EventQueue.java:35)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

java.lang.NullPointerException
    at com.t3.util.guidreference.ZoneReference.resolveReference(ZoneReference.java:21)
    at com.t3.util.guidreference.ZoneReference.resolveReference(ZoneReference.java:1)
    at com.t3.util.guidreference.GUIDReference.value(GUIDReference.java:43)
    at com.t3.util.guidreference.CachedGUIDReference.value(CachedGUIDReference.java:24)
    at com.t3.util.guidreference.NullHelper.value(NullHelper.java:19)
    at com.t3.model.drawing.RadiusTemplate.getBounds(RadiusTemplate.java:123)
    at com.t3.client.ui.zone.PartitionedDrawableRenderer.createChunk(PartitionedDrawableRenderer.java:208)
    at com.t3.client.ui.zone.PartitionedDrawableRenderer.renderDrawables(PartitionedDrawableRenderer.java:117)
    at com.t3.client.ui.zone.ZoneRenderer.renderDrawableOverlay(ZoneRenderer.java:1745)
    at com.t3.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1081)
    at com.t3.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:689)
    at javax.swing.JComponent.paint(JComponent.java:1053)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JComponent.paintChildren(JComponent.java:886)
    at javax.swing.JComponent.paint(JComponent.java:1062)
    at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
    at javax.swing.JComponent.paintToOffscreen(JComponent.java:5223)
    at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
    at javax.swing.RepaintManager.paint(RepaintManager.java:1265)
    at javax.swing.JComponent._paintImmediately(JComponent.java:5171)
    at javax.swing.JComponent.paintImmediately(JComponent.java:4982)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:824)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:807)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:807)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:782)
    at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:731)
    at javax.swing.RepaintManager.access$1300(RepaintManager.java:64)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1720)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at com.t3.client.swing.T3EventQueue.dispatchEvent(T3EventQueue.java:35)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I have uploaded the game file with this bug here: http://ovh.to/T8qWFvc 
The affected map is "Abandoned Fort" one.

**Comment by virenerus** [comment]
Thanks for the report. I try to fix it tomorrow or on monday. I did not
have too much time the past weeks and the solution for tree properties is
more complicated than I thought.
Am 02.11.2014 00:15 schrieb "MoraFermi" notifications@github.com:

**Comment by virenerus** [comment]
I can't reproduce the bug myself. Your file throws the exception though. It seems to be corrupted out of some reasons-.- (There is also at least one image missing in the cmpgn file)
Can you post a more detailed list of steps that reproduce this bug on your machine?

The problem is that the stored template points to a map that is not part of the campaign file. I am not sure how this could happen-.-
