### ISSUE TITLE
Crash in 4.6/Server&Client only

### ISSUE THREAD

**Issue by mbbhudgins** [virenerus/tabletoptool#34]
When running a session of T3, in 4.6 if a player drops a token that no one else has, the traditional question mark shows up however, the token never loads, instead of anyone clicks on the question mark icon, the application will crash.

Not sure the underlying cause. Will be testing further. Rolling back to 4.5 fixes the issue.

**Comment by mbbhudgins** [comment]
Further information while re-creating error

```
java.lang.NullPointerException
    at com.t3.model.AssetManager.putAsset(AssetManager.java:193)
    at com.t3.networking.ServerMethodHandler.putAsset(ServerMethodHandler.java:431)
    at com.t3.networking.ServerMethodHandler.handleMethod(ServerMethodHandler.java:108)
    at com.t3.networking.ServerMethodHandler.handleMethod(ServerMethodHandler.java:53)
    at com.t3.clientserver.handler.AbstractMethodHandler.handleMessage(AbstractMethodHandler.java:23)
    at com.t3.clientserver.connection.AbstractConnection.dispatchMessage(AbstractConnection.java:56)
    at com.t3.clientserver.connection.ServerConnection.handleMessage(ServerConnection.java:71)
    at com.t3.clientserver.connection.AbstractConnection.dispatchMessage(AbstractConnection.java:56)
    at com.t3.clientserver.connection.ClientConnection$ReceiveThread.run(ClientConnection.java:181)
```

Will be looking into this as I work on fixing some other issues

**Comment by virenerus** [comment]
Thanks. I have my last exam this week. After that there is time again to work on this. I fix it as soon as possible.

**Comment by mbbhudgins** [comment]
This error lies in the serialization and deserialization of the token object through the Kryo library; more specifically the dropping of image data
